### ISSUE TITLE
api returns invalid '--' result for AdRelevance although schema defines as arrayofints

### ISSUE THREAD

**Issue by pentium10** [MicrosoftDocs/Advertising-docs#803] opened 2020-04-24 19:57 UTC
AdRelevance is defined as array of int but we still get '--' invalid results. 

Error while reading data, error message: Could not parse '--' as DOUBLE for field AdRelevance (position 20) starting at location 267986

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 3a28373f-29df-e690-957b-0ab591ccd0dd
* Version Independent ID: 74ff38a1-6572-2eba-edad-abe8e9640c29
* Content: [KeywordPerformanceReportFilter Data Object - Reporting - Microsoft Advertising](https://docs.microsoft.com/en-us/advertising/reporting-service/keywordperformancereportfilter?view=bingads-13#feedback)
* Content Source: [Advertising/bingads-13/reporting-service/keywordperformancereportfilter.md](https://github.com/MicrosoftDocs/Advertising-docs/blob/master/Advertising/bingads-13/reporting-service/keywordperformancereportfilter.md)
* Service: **bing-ads-reporting-service**
* GitHub Login: @eric-urban
* Microsoft Alias: **eur**

**Comment by pentium10** [comment] 2020-04-29 15:34
@eric-urban any feedback?

**Comment by eric-urban** [comment] 2020-04-29 16:37
@pentium10 the data type depends on context e.g., the filter is more strict compared to the possible values described in [KeywordPerformanceReportColumn value set](https://docs.microsoft.com/en-us/advertising/reporting-service/keywordperformancereportcolumn?view=bingads-13#adrelevance). If you are attempting to filter by '--' we can consider a string data type in the future. Please let me know if you have any follow up questions or concerns.

**Comment by pentium10** [comment] 2020-04-29 16:48
More context.

We are doing a data export, and the CSV comes with invalid fields matching the schema. 
The schema was set as INT for AdRelevance but the CSV still returns "--" as values as seen in the output. The CSV is not requested from you. 

![image](https://user-images.githubusercontent.com/465691/80622742-e52ae880-8a51-11ea-9f6c-10d37c34d97e.png)

We read that: 
> The value in the report will be "--" (double dash) if the score was not computed.

But that is impractical in real life. 
For example auto import the report to BigQuery as a database no longer works since this change. And defining the columns as string doesn't make sense. Why and empty value is not good enough? 

Also if that is true, than the schema should be modified to STRING on your end not keep as ARRAYOFINTS?

**Comment by eric-urban** [comment] 2020-04-29 17:08
@pentium10 I confirmed the possible values described in the [KeywordPerformanceReportColumn value set](https://docs.microsoft.com/en-us/advertising/reporting-service/keywordperformancereportcolumn?view=bingads-13#adrelevance) are by design e.g., "--" (double dash) if the score was not computed. Since the filter is array of int, you could only filter by 1, 2, and 3. The filter data type does not support filtering by "--" (double dash). The feedback is great, and you raise a fair question why not just leave the field empty for this scenario. The change was implemented [from v12 to v13](https://docs.microsoft.com/en-us/advertising/guides/migration-guide?view=bingads-13#reporting-score-unavailable), and we will consider how to make it more flexible in a future release.

**Comment by pentium10** [comment] 2020-04-29 17:14
there are a bunch of Business Insight tools that use autoSchema from CSV files
all these tools now have struggle to import this kind of dataset 

It should be reverted. This was a backward incompatible change.

**Comment by pentium10** [comment] 2020-04-29 20:42
On other notes, relaxing the schema of an existing database from int to string, looses the "long term storage" price benefits that people have acquired (where this db cost model applies).

**Comment by eric-urban** [comment] 2020-07-15 15:33
@pentium10 I do see your point, and I agree "--" is not ideal. We are evaluating a new optional request parameter to return empty instead of "--". This is not yet confirmed, but I wanted to let you know discussions are active.

**Comment by eric-urban** [comment] 2020-08-28 15:37
@pentium10 thanks again for the feedback and the team is tracking this for a future API version. Since there is no documentation bug/issue to track, I'll close this GitHub issue.

**Closed by eric-urban** 2020-08-28 15:37 UTC
